"use client";

import { useEffect, useRef, useState } from "react";
import icons from "./icons.json";
import WatchScreen, { type WatchMedia } from "./WatchScreen";
import { youtubeEmbedUrl } from "./lib/youtube";

type Media = { id: string; title: string; url: string; source: string; favorite: boolean; watched: boolean; added: number };
const sources = [{name:"All",color:"#c2b4ff"},{name:"My videos",color:"#c2b4ff"},{name:"YouTube",color:"#ff5a6a"},{name:"Bilibili",color:"#39c5e8"},{name:"X",color:"#cbd0d6"},{name:"Web",color:"#7fd6a8"}];
const navigation = [{id:"all",label:"All media"},{id:"recent",label:"Recently added"},{id:"fav",label:"Favorites"},{id:"history",label:"Watch history"},{id:"public",label:"YouTube Picks"},{id:"browse",label:"Shuffle"},{id:"plaza",label:"Subscriptions"}];
function Icon({name}: {name: string}) {return <span className="ico" aria-hidden="true" dangerouslySetInnerHTML={{__html:icons[name as keyof typeof icons] || ""}}/>;}
export default function Home() {
 const [media,setMedia]=useState<Media[]>([]),[ready,setReady]=useState(false),[view,setView]=useState("recent"),[source,setSource]=useState("All"),[query,setQuery]=useState(""),[layout,setLayout]=useState("grid"),[menu,setMenu]=useState(false),[modal,setModal]=useState(""),[url,setUrl]=useState(""),[title,setTitle]=useState(""),[error,setError]=useState(""),[selecting,setSelecting]=useState(false),[selected,setSelected]=useState<string[]>([]),[notice,setNotice]=useState(""),[light,setLight]=useState(false);
 const [playing,setPlaying]=useState<Media | null>(null);
 const dialog=useRef<HTMLDialogElement>(null);
 // Hydrate device-local data after SSR; the initial render must match the server.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{try {const saved=JSON.parse(localStorage.getItem("vvid-local-library")||"[]");if(Array.isArray(saved))setMedia(saved.filter(x=>x&&typeof x.url==="string"&&typeof x.title==="string"&&/^https?:\/\//.test(x.url)));setLight(localStorage.getItem("vvid-local-theme")==="light");const watchId=new URLSearchParams(window.location.search).get("watch");if(Array.isArray(saved)){const resume=saved.find(x=>x.id===watchId&&youtubeEmbedUrl(x.url));if(resume)setPlaying(resume);}}catch{}setReady(true)},[]);
 // Surface a storage failure without losing the in-memory library.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{if(ready)try{localStorage.setItem("vvid-local-library",JSON.stringify(media));}catch{setNotice("Your browser could not save this library. Keep this tab open.");}},[media,ready]);
 useEffect(()=>{document.documentElement.dataset.theme=light?"light":"dark";if(ready)try{localStorage.setItem("vvid-local-theme",light?"light":"dark")}catch{}},[light,ready]);
 useEffect(()=>{if(modal)dialog.current?.showModal();else dialog.current?.close()},[modal]);
 useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(""),4500);return()=>clearTimeout(timer)},[notice]);
 let visible=media.filter(item=>(source==="All"||item.source===source)&&(view!=="fav"||item.favorite)&&(view!=="history"||item.watched)&&(view!=="public"||item.source==="YouTube")&&(view!=="plaza")&&`${item.title} ${item.url}`.toLowerCase().includes(query.toLowerCase()));
 visible=[...visible].sort((a,b)=>b.added-a.added);
 const heading=navigation.find(n=>n.id===view)?.label||"All media";
 const subtitle=view==="recent"?"Recently tucked into your pillow":view==="fav"?"The favorites you lit up yourself":view==="history"?"Pick up where you left off":view==="public"?"Your saved YouTube favorites":view==="plaza"?"Keep your favorite creators close":"Softly tucking away every frame";
 function openAdd(){setError("");setUrl("");setTitle("");setModal("add")}
 function navigate(next:string){setView(next);setMenu(false);setSelected([]);setSelecting(false);if(next==="browse"&&media.length){const item=media[crypto.getRandomValues(new Uint32Array(1))[0] % media.length];setQuery(item.title);setSource("All");}else setQuery("");}
 function save(event:React.FormEvent){event.preventDefault();try{const parsed=new URL(url);if(!["http:","https:"].includes(parsed.protocol))throw Error();if(media.some(x=>x.url===parsed.href)){setError("This link is already in your library.");return;}const host=parsed.hostname.replace(/^www\./,"");const source=host==="youtube.com"||host.endsWith(".youtube.com")||host==="youtu.be"?"YouTube":host==="bilibili.com"||host.endsWith(".bilibili.com")?"Bilibili":host==="x.com"||host==="twitter.com"?"X":/\.(mp4|webm|mov)$/i.test(parsed.pathname)?"My videos":"Web";setMedia(m=>[{id:crypto.randomUUID(),title:title.trim()||host,url:parsed.href,source,favorite:false,watched:false,added:Date.now()},...m]);setModal("");setView("recent");setSource("All");setQuery("");setNotice("Link tucked into your library");}catch{setError("Enter a valid link starting with https:// or http://.")}}
 useEffect(()=>{function onHistory(){const id=new URLSearchParams(window.location.search).get("watch");setPlaying(media.find(x=>x.id===id&&youtubeEmbedUrl(x.url))||null);}window.addEventListener("popstate",onHistory);return()=>window.removeEventListener("popstate",onHistory);},[media]);
 function chooseVideo(item:WatchMedia,replace=false){const found=media.find(x=>x.id===item.id);if(!found)return;setPlaying(found);const address=new URL(window.location.href);address.searchParams.set("watch",item.id);if(replace)window.history.replaceState({vvidWatch:true},"",address);else window.history.pushState({vvidWatch:true},"",address);setMedia(m=>m.map(x=>x.id===item.id?{...x,watched:true}:x));window.scrollTo(0,0);}
 function backToLibrary(){setPlaying(null);if(window.history.state?.vvidWatch)window.history.back();else {const address=new URL(window.location.href);address.searchParams.delete("watch");window.history.replaceState(null,"",address);}}
 function playMedia(event:React.MouseEvent<HTMLAnchorElement>, item:Media){
  if(selecting){event.preventDefault();toggle(item.id);return;}
  if(event.metaKey||event.ctrlKey||event.shiftKey||event.altKey)return;
  if(youtubeEmbedUrl(item.url)){event.preventDefault();chooseVideo(item);}
  setMedia(m=>m.map(x=>x.id===item.id?{...x,watched:true}:x));
 }
 function toggle(id:string){setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id])}
 if(playing)return <WatchScreen item={playing} media={media} onBack={backToLibrary} onChoose={item=>chooseVideo(item,true)}/>;
 return <><div className="app">
 <aside className={`sidebar ${menu?"open":""}`} aria-label="Main navigation"><div className="side-head"><div className="brand"><div className="logo">vv</div><div>vvid<span className="tld">.tv</span><small>Personal media manager</small></div></div></div><div className="side-scroll"><div className="side-label">Library</div>{navigation.map((n,i)=><div key={n.id}>{i===4&&<div className="side-label">Discover</div>}<button className={`nav-item ${view===n.id?"active":""}`} onClick={()=>navigate(n.id)} aria-current={view===n.id?"page":undefined}><Icon name={n.id}/><span>{n.label}</span>{i<4||n.id==="plaza"?<span className="cnt">{n.id==="fav"?media.filter(x=>x.favorite).length:n.id==="history"?media.filter(x=>x.watched).length:n.id==="plaza"?0:media.length}</span>:n.id==="public"?<span className="chev">›</span>:null}</button></div>)}</div><div className="local-foot"><span className="local-dot"/>Local library<span>{media.length} links</span></div></aside>
 {menu&&<button className="mobile-scrim" aria-label="Close navigation" onClick={()=>setMenu(false)}/>}
 <main className="main"><div className="topstick"><div className="topbar"><button className="icon-btn mobile-menu" aria-label="Open navigation" onClick={()=>setMenu(true)}>☰</button><div className={`search ${query?"has-text":""}`}><span className="ico">🔍</span><input aria-label="Search library" placeholder="Search YouTube / my library…" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button className="clr" aria-label="Clear search" onClick={()=>setQuery("")}>✕</button>}</div><button className="icon-btn txt tutorial-button" onClick={()=>setModal("tutorial")}>📖 Tutorial</button><button className="icon-btn bell" aria-label="Updates" onClick={()=>setModal("updates")}><Icon name="bell"/></button><button className="theme-switch" aria-label={light?"Use dark theme":"Use light theme"} onClick={()=>setLight(!light)}>{light?"☾":"☀"}</button><button className="icon-btn accent" aria-label="Add link" onClick={openAdd}>＋</button></div><div className="sources" aria-label="Filter by source">{sources.map(s=><button key={s.name} className={`chip ${source===s.name?"active":""}`} aria-pressed={source===s.name} onClick={()=>setSource(s.name)}><span className="swatch" style={{background:s.color}}/>{s.name}<span className="chip-cnt">{s.name==="All"?media.length:media.filter(m=>m.source===s.name).length}</span></button>)}</div></div>
 <div className="content-head"><div className="title-wrap"><h2>{heading}</h2><p>{subtitle}</p></div><div className="view-actions"><button className={`icon-btn txt ${selecting?"selected-control":""}`} onClick={()=>{setSelecting(!selecting);setSelected([])}} aria-pressed={selecting}>☑️ Select</button><div className="view-toggle"><button className={layout==="grid"?"active":""} aria-label="Grid view" aria-pressed={layout==="grid"} onClick={()=>setLayout("grid")}><Icon name="grid"/></button><button className={layout==="list"?"active":""} aria-label="List view" aria-pressed={layout==="list"} onClick={()=>setLayout("list")}><Icon name="list"/></button></div></div></div>
 <div className="scroll-area">{visible.length===0?<div className="empty show"><div className="blob">{query?"🔍":view==="fav"?"💜":view==="history"?"🕰️":view==="plaza"?"🧭":"🫧"}</div><h3>{query?"No matching links":view==="fav"?"Your favorites belong here":view==="history"?"Your next watch starts here":view==="plaza"?"Your creators, all together":"Nothing here yet"}</h3><p>{query?"Try another search or clear your filters.":view==="fav"?"Tap the heart on a saved link to keep it close.":view==="history"?"Open a saved link and it will show up here.":view==="plaza"?"Save a creator’s channel link to your local library to find them again.":"Tuck your favorite video links into this pillow, or try another source / clear the search."}</p><button className="btn-primary" onClick={query?()=>{setQuery("");setSource("All")}:openAdd}>{query?"Clear search":"＋ Add your first link"}</button></div>:<div className={`media-items ${layout}`}>{visible.map(item=><article className={`media-card ${selected.includes(item.id)?"is-selected":""}`} key={item.id}>{selecting&&<input type="checkbox" className="media-check" aria-label={`Select ${item.title}`} checked={selected.includes(item.id)} onChange={()=>toggle(item.id)}/>}<a className="media-art" href={item.url} target="_blank" rel="noopener noreferrer" onClick={event=>playMedia(event,item)}><span className="play-symbol">▶</span><span className="source-label">{item.source}</span></a><div className="media-info"><a href={item.url} target="_blank" rel="noopener noreferrer" onClick={event=>playMedia(event,item)}>{item.title}</a><p>{new URL(item.url).hostname} · {new Date(item.added).toLocaleDateString()}</p></div><button className={`favorite ${item.favorite?"on":""}`} aria-label={`${item.favorite?"Unfavorite":"Favorite"} ${item.title}`} onClick={()=>setMedia(m=>m.map(x=>x.id===item.id?{...x,favorite:!x.favorite}:x))}>{item.favorite?"♥":"♡"}</button></article>)}</div>}</div>
 </main></div>
 {selecting&&<div className="selection-bar"><span>{selected.length} selected</span><button onClick={()=>setSelected(visible.map(x=>x.id))}>Select all</button><button disabled={!selected.length} onClick={()=>setModal("delete")}>Delete</button><button onClick={()=>{setSelecting(false);setSelected([])}}>Cancel</button></div>}
 <dialog ref={dialog} className="library-dialog" onCancel={()=>setModal("")} onClick={e=>{if(e.target===e.currentTarget)setModal("")}}><div className="dialog-inner"><button className="dialog-close" aria-label="Close dialog" onClick={()=>setModal("")}>✕</button>{modal==="add"?<form onSubmit={save}><div className="dialog-emoji">🔗</div><h2>Add a link</h2><p>A little home for something worth watching.</p><label htmlFor="media-url">Video or website link</label><input id="media-url" type="url" autoFocus required placeholder="https://www.youtube.com/watch?v=…" value={url} onChange={e=>setUrl(e.target.value)}/><label htmlFor="media-title">Title <span>(optional)</span></label><input id="media-title" placeholder="Give it a name you’ll remember" value={title} onChange={e=>setTitle(e.target.value)} maxLength={160}/>{error&&<p className="form-error" role="alert">{error}</p>}<button className="btn-primary submit" type="submit">＋ Add to library</button><small>Saved in this browser, on this device.</small></form>:modal==="tutorial"?<><div className="dialog-emoji">🫧</div><h2>Your own little media library</h2><p>Everything you want to watch, softly tucked away.</p><ol className="tutorial-steps"><li><b>Find something you love</b><p>Copy a video, channel, or website link.</p></li><li><b>Make room for it here</b><p>Tap ＋, paste your link, and give it a title.</p></li><li><b>Come back whenever</b><p>Search, filter, or tap a heart to find your favorites. Your library stays in this browser.</p></li></ol><button className="btn-primary submit" onClick={openAdd}>Add your first link</button></>:modal==="delete"?<><div className="dialog-emoji">🗑️</div><h2>Remove {selected.length} links?</h2><p>This removes the selected links from your local library.</p><button className="btn-primary submit" onClick={()=>{setMedia(m=>m.filter(x=>!selected.includes(x.id)));setSelected([]);setSelecting(false);setModal("");setNotice("Selected links removed")}}>Remove links</button><button className="cancel-button" onClick={()=>setModal("")}>Keep them</button></>:<><div className="dialog-emoji">🔔</div><h2>A place for every frame</h2><p>Your local library is ready. Save links, organize favorites, and switch between grid and list views.</p><div className="update-note"><b>About this project</b><p>This recreation stores your media on this device. Online accounts, creator subscriptions, and live YouTube discovery are not connected.</p></div><button className="btn-primary submit" onClick={()=>setModal("")}>Got it</button></>}</div></dialog>
 {notice&&<div className="local-toast" role="status">✓ {notice}</div>}</>;
}
